services:
    davidiq.captchaplus.service:
        class: davidiq\captchaplus\service
        arguments:
            - '@user'
            - '@auth'
            - '@config'
            - '@captcha.factory'

    davidiq.captchaplus.listener:
        class: davidiq\captchaplus\event\main_listener
        arguments:
            - '@davidiq.captchaplus.service'
        tags:
            - { name: event.listener }
