services:
    davidiq.captchaplus.listener:
        class: davidiq\captchaplus\event\main_listener
        arguments:
            - '@user'
            - '@auth'
            - '@config'
            - '@captcha.factory'
        tags:
            - { name: event.listener }
